import { consts } from '../constants/constants';
import { saveFile } from './save-file';
import { saveFileMultiple } from './save-file-multiple';

export function saveFiles() {
	saveFile('agricultural-lands', 'agriculturalLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('arable-lands', 'arableLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('artificially-irrigated-lands', 'artificiallyIrrigatedLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('border-countries', 'borderCountries', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('border-maps', 'borderMaps', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('borders', 'borders', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('climates', 'climates', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('climates-zones', 'climateZones', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('coasts', 'coasts', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('countries', 'countries', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('domain-areas', 'domainAreas', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('elevations', 'elevations', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('forest-lands', 'forestLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('geographic-notes', 'geographicNotes', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('images', 'images', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('land-uses', 'landUses', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('locations', 'locations', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('maritime-claims', 'maritimeClaims', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('national-flags', 'nationalFlags', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('natural-hazards', 'naturalHazards', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('natural-resources', 'naturalResources', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('other-lands', 'otherLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('permanent-crops-lands', 'permanentCropsLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('permanent-pasture-lands', 'permanentPastureLands', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('region-maps', 'regionMaps', consts.ONTOLOGY.MAIN_ONT_PATH);
	saveFile('terrains', 'terrains', consts.ONTOLOGY.MAIN_ONT_PATH);
};