import { getBackground } from './background';
import { getBorderMapImg } from './border-map-image';
import { getBorders } from './borders';
import { getClimate } from './climate';
import { getCoastLength } from './coast-length';
import { getArea } from './domain-area';
import { getElevation } from './elevation';
import { getGeographicNotes } from './geographic-notes';
import { getGeography } from './geography';
import { getGeographyCoordinates } from './geography-coordinates';
import { getIrrigatedLand } from './irrigated-land';
import { getLandUses } from './land-uses';
import { getMaritimeClaims } from './maritime-claims';
import { getFlag } from './national-flag';
import { getNaturalHazard } from './natural-hazards';
import { getNaturalResources } from './natural-resources';
import { getPopDist } from './population-distribution';
import { getRegionMapImg } from './region-map-image';
import { getSupplementalImages } from './supplemental-image';
import { getTerrains } from './terrain';
export declare const dataScrapers: {
    getArea: typeof getArea;
    getBackground: typeof getBackground;
    getBorderMapImg: typeof getBorderMapImg;
    getBorders: typeof getBorders;
    getClimate: typeof getClimate;
    getCoastLength: typeof getCoastLength;
    getElevation: typeof getElevation;
    getFlag: typeof getFlag;
    getGeographicNotes: typeof getGeographicNotes;
    getGeography: typeof getGeography;
    getGeographyCoordinates: typeof getGeographyCoordinates;
    getIrrigatedLand: typeof getIrrigatedLand;
    getLandUses: typeof getLandUses;
    getMaritimeClaims: typeof getMaritimeClaims;
    getNaturalHazard: typeof getNaturalHazard;
    getNaturalResources: typeof getNaturalResources;
    getPopDist: typeof getPopDist;
    getRegionMapImg: typeof getRegionMapImg;
    getSupplementalImages: typeof getSupplementalImages;
    getTerrains: typeof getTerrains;
};
