"use strict";
// import * as Logger from 'node_modules/simple-node-logger/index';
Object.defineProperty(exports, "__esModule", { value: true });
var globalStore_1 = require("../constants/globalStore");
var load_file_1 = require("./load-file");
function loadFiles() {
    var LOG_FILE_NAME = 'logs/log-' + ((new Date()).toISOString()).replace(':', '-').replace(':', '-').replace('.', '-').trim() + '.log';
    // store.LOG_STREAM = Logger.createSimpleFileLogger(LOG_FILE_NAME);
    globalStore_1.store.LOG_FILE_NAME = LOG_FILE_NAME;
    load_file_1.loadFile('agricultural-lands', 'agriculturalLands');
    load_file_1.loadFile('arable-lands', 'arableLands');
    load_file_1.loadFile('artificially-irrigated-lands', 'artificiallyIrrigatedLands');
    load_file_1.loadFile('border-countries', 'borderCountries');
    load_file_1.loadFile('border-maps', 'borderMaps');
    load_file_1.loadFile('borders', 'borders');
    load_file_1.loadFile('climates', 'climates');
    load_file_1.loadFile('climates-zones', 'climatesZones');
    load_file_1.loadFile('coasts', 'coasts');
    load_file_1.loadFile('countries', 'countries', true);
    load_file_1.loadFile('domain-areas', 'domainAreas');
    load_file_1.loadFile('forest-lands', 'forestLands');
    load_file_1.loadFile('geographic-notes', 'geographicNotes');
    load_file_1.loadFile('images', 'images');
    load_file_1.loadFile('land-uses', 'landUses');
    load_file_1.loadFile('locations', 'locations');
    load_file_1.loadFile('maritime-claims', 'maritimeClaims');
    load_file_1.loadFile('national-flags', 'nationalFlags');
    load_file_1.loadFile('natural-hazards', 'naturalHazards');
    load_file_1.loadFile('natural-resources', 'naturalResources');
    load_file_1.loadFile('other-lands', 'otherLands');
    load_file_1.loadFile('permanent-crops-lands', 'permanentCropsLands');
    load_file_1.loadFile('permanent-pasture-lands', 'permanentPastureLands');
    load_file_1.loadFile('region-maps', 'regionMaps');
    load_file_1.loadFile('terrains', 'terrains');
}
exports.loadFiles = loadFiles;
;
