"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var constants_1 = require("../constants/constants");
var save_file_1 = require("./save-file");
function saveFiles() {
    save_file_1.saveFile('agricultural-lands', 'agriculturalLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('arable-lands', 'arableLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('artificially-irrigated-lands', 'artificiallyIrrigatedLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('border-countries', 'borderCountries', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('border-maps', 'borderMaps', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('borders', 'borders', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('climates', 'climates', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('climates-zones', 'climateZones', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('coasts', 'coasts', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('countries', 'countries', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('domain-areas', 'domainAreas', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('elevations', 'elevations', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('forest-lands', 'forestLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('geographic-notes', 'geographicNotes', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('images', 'images', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('land-uses', 'landUses', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('locations', 'locations', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('maritime-claims', 'maritimeClaims', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('national-flags', 'nationalFlags', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('natural-hazards', 'naturalHazards', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('natural-resources', 'naturalResources', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('other-lands', 'otherLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('permanent-crops-lands', 'permanentCropsLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('permanent-pasture-lands', 'permanentPastureLands', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('region-maps', 'regionMaps', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
    save_file_1.saveFile('terrains', 'terrains', constants_1.consts.ONTOLOGY.MAIN_ONT_PATH);
}
exports.saveFiles = saveFiles;
;
