const isoCodeToDataCodeTable = {
    ye: 'ym', YE: 'ym',
    ru: 'rs', RU: 'rs',
    ua: 'up', UA: 'up',
    hn: 'ho', HN: 'ho',
    tr: 'tu', TR: 'tu',
    de: 'gm', DE: 'gm',
    sk: 'lo', SK: 'lo',
    cc: 'ck', CC: 'ck',
    ph: 'rp', PH: 'rp',
    ky: 'cj', KY: 'cj',
    vg: 'vi', VG: 'vi',
    bs: 'bf', BS: 'bf',
    cl: 'ci', CL: 'ci',
    mm: 'bm', MM: 'bm',
    dz: 'ag', DZ: 'ag',
    ie: 'ei', IE: 'ei',
    vu: 'nh', VU: 'nh',
    me: 'mj', ME: 'mj',
    zw: 'zi', ZW: 'zi',
    iq: 'iz', IQ: 'iz',
    jp: 'ja', JP: 'ja',
    pt: 'po', PT: 'po',
    aw: 'aa', AW: 'aa',
    bz: 'bh', BZ: 'bh',
    yt: 'fr', YT: 'fr',
    tc: 'tk', TC: 'tk',
    gu: 'gq', GU: 'gq',
    km: 'cn', KM: 'cn',
    tg: 'to', TG: 'to',
    sd: 'su', SD: 'su',
    kh: 'cb', KH: 'cb',
    pw: 'ps', PW: 'ps',
    ki: 'kr', KI: 'kr',
    gf: 'fr', GF: 'fr',
    az: 'aj', AZ: 'aj',
    py: 'pa', PY: 'pa',
    bi: 'by', BI: 'by',
    mw: 'mi', MW: 'mi',
    lk: 'ce', LK: 'ce',
    as: 'aq', AS: 'aq',
    ad: 'an', AD: 'an',
    ai: 'av', AI: 'av',
    aq: 'ay', AQ: 'ay',
    ag: 'ac', AG: 'ac',
    au: 'as', AU: 'as',
    at: 'au', AT: 'au',
    bh: 'ba', BH: 'ba',
    bd: 'bg', BD: 'bg',
    by: 'bo', BY: 'bo',
    bj: 'bn', BJ: 'bn',
    bm: 'bd', BM: 'bd',
    bo: 'bl', BO: 'bl',
    ba: 'bk', BA: 'bk',
    bw: 'bc', BW: 'bc',
    bn: 'bx', BN: 'bx',
    bg: 'bu', BG: 'bu',
    bf: 'uv', BF: 'uv',
    cf: 'ct', CF: 'ct',
    td: 'cd', TD: 'cd',
    cn: 'ch', CN: 'ch',
    cx: 'kt', CX: 'kt',
    cd: 'cg', CD: 'cg',
    cg: 'cf', CG: 'cf',
    ck: 'cw', CK: 'cw',
    cr: 'cs', CR: 'cs',
    ci: 'iv', CI: 'iv',
    cw: 'uc', CW: 'uc',
    cz: 'ez', CZ: 'ez',
    dk: 'da', DK: 'da',
    dm: 'do', DM: 'do',
    do: 'dr', DO: 'dr',
    sv: 'es', SV: 'es',
    gq: 'ek', GQ: 'ek',
    ee: 'en', EE: 'en',
    sz: 'wz', SZ: 'wz',
    pf: 'fp', PF: 'fp',
    tf: 'fs', TF: 'fs',
    ga: 'gb', GA: 'gb',
    gm: 'ga', GM: 'ga',
    ps: 'we', PS: 'we',
    ge: 'gg', GE: 'gg',
    gd: 'gj', GD: 'gj',
    gg: 'gk', GG: 'gk',
    gn: 'gv', GN: 'gv',
    gw: 'pu', GW: 'pu',
    ht: 'ha', HT: 'ha',
    va: 'vt', VA: 'vt',
    is: 'ic', IS: 'ic',
    il: 'is', IL: 'is',
    kp: 'kn', KP: 'kn',
    kr: 'ks', KR: 'ks',
    xk: 'kv', XK: 'kv',
    kw: 'ku', KW: 'ku',
    lv: 'lg', LV: 'lg',
    lb: 'le', LB: 'le',
    ls: 'lt', LS: 'lt',
    lr: 'li', LR: 'li',
    li: 'ls', LI: 'ls',
    lt: 'lh', LT: 'lh',
    mo: 'mc', MO: 'mc',
    mg: 'ma', MG: 'ma',
    mh: 'rm', MH: 'rm',
    mq: 'mb', MQ: 'mb',
    mu: 'mp', MU: 'mp',
    mc: 'mn', MC: 'mn',
    mn: 'mg', MN: 'mg',
    ms: 'mh', MS: 'mh',
    ma: 'mo', MA: 'mo',
    na: 'wa', NA: 'wa',
    ni: 'nu', NI: 'nu',
    ne: 'ng', NE: 'ng',
    ng: 'ni', NG: 'ni',
    nu: 'ne', NU: 'ne',
    mp: 'cq', MP: 'cq',
    om: 'mu', OM: 'mu',
    pa: 'pm', PA: 'pm',
    pg: 'pp', PG: 'pp',
    pn: 'pc', PN: 'pc',
    pr: 'rq', PR: 'rq',
    bl: 'tb', BL: 'tb',
    kn: 'sc', KN: 'sc',
    lc: 'st', LC: 'st',
    mf: 'rn', MF: 'rn',
    pm: 'sb', PM: 'sb',
    st: 'tp', ST: 'tp',
    sn: 'sg', SN: 'sg',
    rs: 'ri', RS: 'ri',
    sc: 'se', SC: 'se',
    sg: 'sn', SG: 'sn',
    sx: 'nn', SX: 'nn',
    sb: 'bp', SB: 'bp',
    za: 'sf', ZA: 'sf',
    gs: 'sx', GS: 'sx',
    ss: 'od', SS: 'od',
    es: 'sp', ES: 'sp',
    sr: 'ns', SR: 'ns',
    sj: 'sv', SJ: 'sv',
    se: 'sw', SE: 'sw',
    ch: 'sz', CH: 'sz',
    tj: 'ti', TJ: 'ti',
    tl: 'tt', TL: 'tt',
    tk: 'tl', TK: 'tl',
    to: 'tn', TO: 'tn',
    tt: 'td', TT: 'td',
    tn: 'ts', TN: 'ts',
    tm: 'tx', TM: 'tx',
    gb: 'uk', GB: 'uk',
    vn: 'vm', VN: 'vm',
    vi: 'vq', VI: 'vq',
    eh: 'wi', EH: 'wi',
    zm: 'za', ZM: 'za'
};

const dataCodeToIsoCodeTable = {
    ag: 'dz',
    aq: 'as',
    an: 'ad',
    av: 'ai',
    ay: 'aq',
    ac: 'ag',
    aa: 'aw',
    as: 'au',
    au: 'at',
    aj: 'az',
    bf: 'bs',
    ba: 'bh',
    bg: 'bd',
    bo: 'by',
    bh: 'bz',
    bn: 'bj',
    bd: 'bm',
    bl: 'bo',
    bk: 'ba',
    bc: 'bw',
    vi: 'vg',
    bx: 'bn',
    bu: 'bg',
    uv: 'bf',
    bm: 'mm',
    by: 'bi',
    cb: 'kh',
    cj: 'ky',
    ct: 'cf',
    cd: 'td',
    ci: 'cl',
    ch: 'cn',
    kt: 'cx',
    ck: 'cc',
    cn: 'km',
    cg: 'cd',
    cf: 'cg',
    cw: 'ck',
    cs: 'cr',
    iv: 'ci',
    uc: 'cw',
    ez: 'cz',
    da: 'dk',
    do: 'dm',
    dr: 'do',
    es: 'sv',
    ek: 'gq',
    en: 'ee',
    wz: 'sz',
    fg: 'gf',
    fp: 'pf',
    fs: 'tf',
    gb: 'ga',
    ga: 'gm',
    gz: 'ps',
    gg: 'ge',
    gm: 'de',
    gj: 'gd',
    gq: 'gu',
    gk: 'gg',
    gv: 'gn',
    pu: 'gw',
    ha: 'ht',
    vt: 'va',
    ho: 'hn',
    ic: 'is',
    iz: 'iq',
    ei: 'ie',
    is: 'il',
    ja: 'jp',
    kr: 'ki',
    kn: 'kp',
    ks: 'kr',
    kv: 'xk',
    ku: 'kw',
    lg: 'lv',
    le: 'lb',
    lt: 'ls',
    li: 'lr',
    ls: 'li',
    lh: 'lt',
    mc: 'mo',
    ma: 'mg',
    mi: 'mw',
    rm: 'mh',
    mb: 'mq',
    mp: 'mu',
    mf: 'yt',
    mn: 'mc',
    mg: 'mn',
    mj: 'me',
    mh: 'ms',
    mo: 'ma',
    wa: 'na',
    nu: 'ni',
    ng: 'ne',
    ni: 'ng',
    ne: 'nu',
    cq: 'mp',
    mu: 'om',
    ps: 'pw',
    pm: 'pa',
    pp: 'pg',
    pa: 'py',
    rp: 'ph',
    pc: 'pn',
    po: 'pt',
    rq: 'pr',
    rs: 'ru',
    tb: 'bl',
    sc: 'kn',
    st: 'lc',
    rn: 'mf',
    sb: 'pm',
    tp: 'st',
    sg: 'sn',
    ri: 'rs',
    se: 'sc',
    sn: 'sg',
    nn: 'sx',
    lo: 'sk',
    bp: 'sb',
    sf: 'za',
    sx: 'gs',
    od: 'ss',
    sp: 'es',
    ce: 'lk',
    su: 'sd',
    ns: 'sr',
    sv: 'sj',
    sw: 'se',
    sz: 'ch',
    ti: 'tj',
    tt: 'tl',
    to: 'tg',
    tl: 'tk',
    tn: 'to',
    td: 'tt',
    ts: 'tn',
    tu: 'tr',
    tx: 'tm',
    tk: 'tc',
    up: 'ua',
    uk: 'gb',
    nh: 'vu',
    vm: 'vn',
    vq: 'vi',
    we: 'ps',
    wi: 'eh',
    ym: 'ye',
    za: 'zm',
    zi: 'zw'
};

export function dataCodeToIsoCode(dataCode: string): string {
    return dataCodeToIsoCodeTable[dataCode] || dataCode;
}

export function isoCodeToDataCode(iso: string): string {
    return isoCodeToDataCodeTable[iso] || iso.toLowerCase();
}
